on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build_iso:
    runs-on: ubuntu-latest
    name: Build ISO
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository_owner }}
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.0
        id: build
        with:
          arch: x86_64
          image_name: hostbazzite
          image_repo: ${{ steps.registry_case.outputs.lowercase }}
          variant: "Kinoite"
          version: 40
          image_tag: latest
          iso_name: "hostbazzite.iso"
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0